# Application properties (Begin with prefix=keysight)
keysight:
    job:
        account:
            name: ACCOUNT_DB_TO_REST
            cron: 0/45 * * 1/1 * ?
            chunkSize: 100
            fetchSize: 200
            batchSize: 10
            mapping:
                 system_id: SystemId
                 system_name: SystemName
                 cust_type: CustomerType
                 accnt_name: AccountName
                 status: Status
                 registry_id: RegistryId
                 alias: Alias
                 name_prnctn: NamePronunciation
                 taxpayer_id: TaxpayerId
                 tax_reg_num: TaxRegistrationNumber
                 cust_category: CustomerCategory
                 accnt_num: AccountNumber
                 accnt_desc: AccountDescription
                 region: Region
                 classification: Classification
                 accnt_type: AccountType
                 sales_channel: SalesChannel
                 reference: Reference
                 nls_code: NLSLanguageCode
                 custname_local_lang: NameLocalLanguage
                 cust_screening: CustomerScreening
                 last_crd_rev_dt: LastCreditReviewDate
                 next_crd_rev_dt: NextCreditReviewDate
                 credit_rev_cycle: CreditReviewCycle
                 par_party: ParentParty
                 emg_last_trans: EmgLastTrans
                 group_desc: GroupingDescription
                 group_id: GroupingId
                 ixia_classification: IXIAClassification
                 profile_class: ProfileClass
        address:
            name: ADDRESS_DB_TO_REST
            cron: 0 0/2 * 1/1 * ?
            chunkSize: 100
            fetchSize: 200
            batchSize: 10
            mapping:
                  MDMAccountId: MDM_ACCOUNT_ID
                  SiteNumber: site_num
                  SiteId: site_id
                  SiteName: site_name
                  SystemId: SYSTEM_ID
                  SystemName: SYSTEM_NAME
                  Status: status
                  AddressLine1: addr_line_1
                  AddressLine2: addr_line_2
                  AddressLine3: addr_line_3
                  AddressLine4: addr_line_4
                  Address: address
                  City: city
                  County: county
                  State: state
                  Province: province
                  PostalCode: postal_code
                  Country: country
                  Addressee: addressee
                  KeysightSFAAddressId: ks_sfa_addr_id
                  IdentifyingAddress: identifying_addr
                  Reference: reference
                  Translation: translation
                  OperatingUnit: oper_unit
                  RPLCheck: rpl_info_user
                  NLSLanguage: nls_lang
                  AddressLine1LocalLanguage: addr_loc_lang_line_1
                  AddressLine2LocalLanguage: addr_loc_lang_line_2
                  AddressLine3LocalLanguage: addr_loc_lang_line_3
                  AddressLine4LocalLanguage: addr_loc_lang_line_4
                  CityLocalLanguage: city_loc_lang
                  StateLocalLanguage: state_loc_lang
                  PostalLocalLanguage: postal_code_loc_lang
                  ProvinceLocalLanguage: province_loc_lang
                  CountyLocalLanguage: county_loc_lang
                  CountryLocalLanguage: country_loc_lang
                  SendAcknowledgement: send_acknldgmnt
                  InvoiceCopies: invoice_cop_sup
                  AccountSiteType: accnt_site_type
                  ContextValue: context_value
                  TaxablePerson: taxable_person
                  IndustryClassification: industry_classification
                  TaxCertificateDate: tax_cert_date
                  BusinessNumber: business_num
                  IndustrySubclassification: indust_sub_classification
                  AddressSiteCategory: addr_site_ctg
                  ATS: ats
                  BusinessPurpose: purpose
                  Location: loc
                  BillToLocation: bill_to_loc
                  PrimaryPurpose: primary_purpose
                  RevenueRecognition: rev_recognition
                  OrgSegment: org_segment
                  SubSegment: sub_segment
                  AccountClass: accnt_class
                  Receivable: receivable
                  Revenue: revenue
                  PaymentTerms: pay_terms
                  SalesPerson: sales_person
                  OrderType: order_type
                  PriceList: price_lst
                  DemandClass: demand_class
                  ReceiptMethods: receipt_method
                  PrimaryPayment: primary_payment
                  StartDate: start_dt
                  EndDate: end_dt
                  DefaultReportingCountryName: default_rpt_country
                  DefaultReportingRegistrationNumber: default_reg_num
                  TaxRegistrationActive: tax_reg_active
                  RegimeCode: regime_cd
                  Tax: tax
                  TaxJurisdictionCode: tax_jurisdiction_cd
                  TaxRegistrationNumber: tax_reg_num
                  Source: source
                  DefaultTaxRegistration: default_tax_reg
                  EfectiveFrom: eff_from_dt
                  EffectiveTo: eff_to_dt
                  RoundingRule: rounding_rule
    queries:
        getPendingAccounts: SELECT * FROM MDM_ACCOUNT WHERE INTERFACE_STATUS='Pending' AND SYSTEM_ID > ':systemId' ORDER BY SYSTEM_ID,SYSTEM_NAME

        getPendingAccountAddresses: SELECT * FROM MDM_ACCOUNT_ADDRESS WHERE INTERFACE_STATUS='Pending' AND SYSTEM_ID > ':systemId' ORDER BY SYSTEM_ID,SYSTEM_NAME

#Spring properties
spring:
    batch:
        job:
            enabled: false
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: lalit
        password: lalit
        url: jdbc:oracle:thin:@localhost:1521:xe
        max-active: 50
        max-idle: 20
        max-wait: 20000
        min-idle: 15
server:
    port: 8033